config/routes.rb
Rails.application.routes.draw do
  root to: 'dogs#index'
  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to @dog
    else
      render 'new'
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to @dog
  end

  def destroy
    dog = Dog.find(params[:id])
    dog.destroy
    flash[:notice] = "Dog was successfully deleted"
    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name,:breed,:age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_dogs.html.erb
<ul>
  <% @dogs.each do |dog| %>
  <li><a href="/dogs/<%=dog.id%>"> <%= dog.name %></a> </li>
  <% end %>
</ul>

app/views/dogs/edit.html.erb
<h1>Let's Edit:</h1>

<%= form_for @dog do |f| %>
  <%=f.text_field :name %>
  <%=f.text_field :breed %>
  <%=f.text_field :age %>
  <%=f.submit 'edit dog' %>
<% end %>

app/views/dogs/index.html.erb
<h1>This is index</h1>
<%= render partial: "dogs", dog: @dogs %>

app/views/dogs/new.html.erb
<h1>This is our new!!!</h1>
<%= form_for :dog, url: dogs_path do |f| %>
  name: <%= f.text_field(:name )%>
  breed: <%= f.text_field(:breed) %>
  age: <%= f.text_field (:age) %>
  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1>This is our show!!!</h1>
<h3>This is: <%= @dog.name %></h3>
<h3>This is a: <%= @dog.breed %></h3>
<h5>They are <%= @dog.age %> years old.</h5>
<%= link_to 'Edit Dog', edit_dog_path %>
<%= link_to 'Delete Dog',dog_path, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudDogs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <nav> <a href="/dogs"><p>home</p></a><a href="/dogs/new"><p>new</p> </a> </nav>
<%= yield %>

</body>
</html>